name: CI

on:
  push:
    branches: [ "main", "master", "NikolaBranch" ]
  pull_request:
    branches: [ "main", "master", "NikolaBranch" ]
    types: [review_requested, review_request_removed, reopened, synchronize, closed]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  check_review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run GitHub Script
        id: github-script
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { octokit } = context;
            try {
              const { data: reviews } = await octokit.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
              const hasOgnjenApproval = reviews.some(review => review.user.login === 'ogsub' && review.state === 'APPROVED');
              if (!hasOgnjenApproval) {
                core.setFailed('Ognjen approval required.');
              }
            } catch (error) {
              core.setFailed(`Error: ${error.message}`);
            }
